### ISSUE TITLE
Provider stores containers in tfstate even on create failure, and doesn't check consistency with world

### ISSUE THREAD

**Issue by pdf** [jtopjian/terraform-provider-lxc#2]
I haven't tracked this down yet (new to terraform), but the result is that if creation fails:

A) You can't fix the problem because this provider doesn't support `update`
B) You can't `destroy` because terraform thinks the containers exist and now can't delete them
C) Refresh has no effect on tfstate

The only option is to blow away tfstate and start again.

**Comment by jtopjian** [comment]
Good point. There's definitely a lot more that can be done with regard to detecting and recovering from failure.

In addition, since I initially made this plugin, Terraform core has added some features that may help. I'll research this.

If you can describe some easy ways of reproducing, though, that'd definitely help.

**Comment by pdf** [comment]
Easiest way to produce failing container creation is to just add something random to `template_extra_args` - I originally discovered this behaviour when they were getting sent out-of-order.

**Comment by jtopjian** [comment]
I think f9bb675bbf98614f17862507bd24de12cc475696 should resolve this. Let me know what you think.

**Comment by pdf** [comment]
LGTM :+1:

**Comment by pdf** [comment]
Actually, I think it needs to register the container as soon as it's created - it may still fail to start, and that will wedge you with the container existing, not being able to be `destroy`ed, and not being able to be created by a subsequent `apply`.

**Comment by jtopjian** [comment]
Good point again.

How about if the container is registered after:

``` go
  if err := c.Create(options); err != nil {
    return err
  }
```

This way, the container will never be registered if `c.Create` fails. If something after this step fails, the container will be registered and _should_ be able to be cleaned up by Terraform. That should be a good balance.

I reviewed a few other Terraform providers (OpenStack, AWS, and DigitalOcean) and all have a window of opportunity for the resource to fail building between registration and build completion. But I think the key is to choose the right point of registration.

**Comment by pdf** [comment]
Yeah, sounds good.

**Comment by jtopjian** [comment]
OK, the latest commit should do it. Hopefully committing directly to master won't bit me in the ass again. :smile:
